blank_issues_enabled: false
contact_links:
  - name: Chrome Web Store Support
    url: https://chromewebstore.google.com/detail/hmkcbieabcldlndhjeemggokhlebjoem
    about: Visit the official Chrome Web Store page for reviews and ratings
  - name: Official Website & Documentation
    url: https://allinone.milanwebportal.com
    about: Learn more about features, privacy policy, and updates
